---
output: html_document
title: "Example auto-numbering"
---
  
```{r number_figures, echo=FALSE}
# This is a knitr hook to enable figure and table captions
# number figures
# from http://stackoverflow.com/a/18672268/1036500
library("knitr")
tn = local({
  i = 0
  function(x) {
    i <<- i + 1
    paste("<table><caption style=\"font-size:1.5em; color:black\"><b>", 'Figure ', i, '</b>: ', x, "</caption><colgroup><col width='500'></col></colgroup><thead><tr class='header'></tr></thead><tbody></tbody></table><p>", sep = '')
  }
})
knit_hooks$set(fig.cap = function(before, options, envir) {
  if(!before)
    tn(options$fig.cap)
})
default_output_hook = knit_hooks$get("output")
knit_hooks$set(output = function(x, options) {
  if (is.null(options$fig.cap) == F)  
    x
  else
    default_output_hook(x,options)
})
# number tables
# from http://stackoverflow.com/a/18672268/1036500
to = local({
  i = 0
  function(x) {
    i <<- i + 1
    paste("<table><caption style=\"font-size:1.5em; color:black\"><b>", 'Table ', i, '</b>: ', x, "</caption><colgroup><col width='500'></col></colgroup><thead><tr class='header'></tr></thead><tbody></tbody></table><p>", sep = '')
  }
})
knit_hooks$set(tab.cap = function(before, options, envir) {
  if(!before)
    to(options$tab.cap)
})
default_output_hook = knit_hooks$get("output")
knit_hooks$set(output = function(x, options) {
  if (is.null(options$tab.cap) == F)  
    x
  else
    default_output_hook(x,options)
})
```


```{r setup, echo=FALSE, message=FALSE}
require(knitr)
require(kfigr) # devtools::install_github("github mkoohafkan/kfigr")
opts_chunk$set(message=FALSE, warning=FALSE)
```

## Examples:

```{r}
library(tidyverse) ## for data, easy plotting
```

Here we show a basic table. Note that the chunk is labeled, anchor = "table", and we define the caption.

```{r carTable, anchor = "table", tab.cap = "Example table content.", fig.align = 'center'}
knitr::kable(head(mtcars, 10))

```


```{r carTable2, tab.cap = "Example table content.", fig.align = 'center'}
knitr::kable(head(mtcars, 10))

```

We can then reference our `r figr('carTable', TRUE, type ="table")` like that.


Based on https://gist.github.com/benmarwick/f3e0cafe668f3d6ff6e5.